### ISSUE TITLE
membership?

### ISSUE THREAD

**Issue by qa960362** [HitomaruKonpaku/stream-crawler#1]
Hi,This can  record membership?

**Comment by HitomaruKonpaku** [comment]
Hi @qa960362 , what do you mean by membership? (Maybe explain more detail on what you want)

**Comment by qa960362** [comment]
youtube and twitcast i have membership

can record ?

**Comment by HitomaruKonpaku** [comment]
For YouTube, I check new live using `/live` so prob won't work with new members stream.

For TwitCasting, it can detect all new stream, but you need to set up yt-dlp cookies for it to record.

**Comment by qa960362** [comment]
I don't know in which file to make changes...

**Comment by qa960362** [comment]
if only
COOKIES.txt
Put in COOKIES folder?

**Comment by HitomaruKonpaku** [comment]
You prob need to check https://github.com/yt-dlp/yt-dlp for more detail

Basically add `--cookies` to `yt-dlp` options

**Comment by qa960362** [comment]
thank
is ok
but yt I'can auto re membership live
